### ISSUE TITLE
Who are you?

### ISSUE THREAD

**Issue by pmario** [feathub/feathub#2]
The website doesn't contain an About info?

**Comment by MichaIng** [comment]
@pmario 
https://feathub.com/ 😃. But yeah, at least this link and some words on the main page would be helpful.

#### EDIT
Ah I guess you already meant the website (not GitHub page). I just stumbled over the same, no "about", imprint or contact there.
@Ecco seems to be involved, but since no contributions have been done on this repo, really nothing else can be derived. At least one "official" contact address should be always available IMO.
